updated

diff --git a/Jenkins/mvn/Jenkinsfile b/Jenkins/mvn/Jenkinsfile
--- a/Jenkins/mvn/Jenkinsfile
+++ b/Jenkins/mvn/Jenkinsfile
@@ -94,25 +94,27 @@ pipeline {
                             println("ECR_REGISTRY: ${ECR_REGISTRY}")
 
                             // when using Kaniko
-                            def status = sh(
-                                script: """
-                                    set -eo pipefail
-                                    cd ${APP_DIR}
-                                    /kaniko/executor \
-                                        --context=dir://\$(pwd)/ \
-                                        --dockerfile=\$(pwd)/Dockerfile \
-                                        --destination=${ECR_REGISTRY}/${ECR_REPO_NAME}:${VERSION} \
-                                        --cache=false \
-                                        --verbosity=info
-                                    echo "✅ Kaniko build done"
-                                """,
-                                returnStatus: true
-                            )
+                            timeout(time: 5, unit: 'MINUTES') { // Adjust timeout as needed, e.g., 5, 10, 15 minutes
+                                def status = sh(
+                                    script: """
+                                        set -eo pipefail
+                                        cd ${APP_DIR}
+                                        /kaniko/executor \\
+                                            --context=dir://\$(pwd)/ \\
+                                            --dockerfile=\$(pwd)/Dockerfile \\
+                                            --destination=${ECR_REGISTRY}/${ECR_REPO_NAME}:${VERSION} \\
+                                            --cache=false \\
+                                            --verbosity=info
+                                        echo "✅ Kaniko build done"
+                                    """,
+                                    returnStatus: true
+                                )
 
-                            if (status != 0) {
-                                error "❌ Kaniko build failed with status ${status}"
-                            } else {
-                                println("✅ build done with status: status ${status}")
+                                if (status != 0) {
+                                    error "❌ Kaniko build failed with status ${status}"
+                                } else {
+                                    println("✅ build done with status: status ${status}")
+                                }
                             }
 
 
